### ISSUE TITLE
Add twitter to botton of website

### ISSUE THREAD

**Issue by sscheele** [wtwcyber/wtwcyber.github.io#1]
Add twitter to the "around the web" section at the bottom of the website. See the [theme page](https://github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/exampleSite/config.toml) for an example of how this looks, and the [icon pack website](http://fontawesome.io/icon/twitter/) for the CSS class.

**Comment by taylanu** [comment]
I've tried hard to stay away from compiling with hugo, but I guess I have to this time ;)

**Comment by taylanu** [comment]
Successfully completed without using Hugo. Closing thread.
